version: 1.13.0.{build}

before_build:
  - nuget restore

after_build:
  - COPY README.md README.txt
  - 7z a TA_Editor-%APPVEYOR_BUILD_VERSION%-%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\TA_Editor\bin\%CONFIGURATION%\* README.txt

artifacts:
  - path: TA_Editor-$(APPVEYOR_BUILD_VERSION)-$(CONFIGURATION).zip
    name: TA_Editor

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

deploy:
  release: v$(APPVEYOR_BUILD_VERSION)
  draft: true
  provider: GitHub
  auth_token:
    secure: glwd3HCPhB64nX2++Co5BhN4vEwqEILuPQG0puwWoFpKTFd21iphYt8Z2QsNiAV1
  artifact: TA_Editor
  on:
    APPVEYOR_REPO_TAG: true
    configuration: Release

configuration:
  - Debug
  - Release

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

matrix:
  fast_finish: true
