version: 1.13.0.{build}

before_build:
  - nuget restore

after_build:
  - 7z a TA_Editor.zip %APPVEYOR_BUILD_FOLDER%\TA_Editor\bin\%Configuration%\* README.md

artifacts:
  - path: TA_Editor.zip

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

deploy: off

configuration:
  - Debug
  - Release

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

matrix:
  fast_finish: true
